{{- if .Values.autoscaling.enabled }}
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: {{ include "github-actions-runner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "github-actions-runner.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "github-actions-runner.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    {{- if .Values.github.repository }}
    repositoryNames:
    - {{ .Values.github.repository }}
    {{- end }}
  {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
  - type: PercentageRunnersBusy
    scaleUpThreshold: '0.75'
    scaleDownThreshold: '0.3'
    scaleUpFactor: '1.4'
    scaleDownFactor: '0.7'
  {{- end }}
{{- end }}
